import fs from 'fs';
import pkg from 'pg';
const { Client } = pkg;
const c = new Client({ connectionString: fs.readFileSync('C:/Users/ISO/.sb_db.url','utf8').trim(), ssl:{rejectUnauthorized:false} });
await c.connect();
const { rows } = await c.query(`select pg_get_functiondef(p.oid) d from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='mos' and p.proname='promo_sugerencias'`);
const live = rows[0].d;
console.log('LEN', live.length, 'CRLF?', live.includes('\r\n'));
console.log('has liderVentas?', live.includes("liderVentas"));
const i = live.indexOf("jsonb_build_object('skuBase', x.l_sku");
console.log('--- items_j ---');
console.log(JSON.stringify(live.slice(i-360, i+260)));
await c.end();
