import fs from 'fs';
import pkg from 'pg';
const { Client } = pkg;
const c = new Client({ connectionString: fs.readFileSync('C:/Users/ISO/.sb_db.url','utf8').trim(), ssl:{rejectUnauthorized:false} });
await c.connect();
const cols = (await c.query(`select string_agg(column_name,',' order by ordinal_position) c from information_schema.columns where table_schema='mos' and table_name='dispositivos'`)).rows[0].c;
console.log('COLS:', cols);
const r = await c.query(`select * from mos.dispositivos where id_dispositivo like '7e57c1a0%'`);
console.dir(r.rows, {depth:3});
await c.end();
