import fs from 'fs';
import pkg from 'pg';
const { Client } = pkg;
const c = new Client({ connectionString: fs.readFileSync('C:/Users/ISO/.sb_db.url','utf8').trim(), ssl:{rejectUnauthorized:false} });
await c.connect();
const q = async (t,s,p)=>{ try{ const r=await c.query(s,p); console.log('###',t); console.dir(r.rows,{depth:4,maxArrayLength:80}); }catch(e){ console.log('###',t,'ERR',e.message); } };
await q('vd_sample', `select vd.sku, vd.cod_barras, vd.nombre, vd.cantidad, v.fecha from me.ventas_detalle vd join me.ventas v on v.id_venta=vd.id_venta order by v.fecha desc limit 8`);
await q('ventas30', `select count(*) lineas, count(distinct vd.sku) skus from me.ventas_detalle vd join me.ventas v on v.id_venta=vd.id_venta where v.fecha >= now() - interval '30 days' and coalesce(v.estado_envio,'') not ilike '%ANULAD%'`);
await q('stock_match', `select count(*) n_stock, count(*) filter (where exists(select 1 from mos.productos p where p.codigo_barra=s.cod_producto)) match_cb, count(*) filter (where exists(select 1 from mos.productos p where p.sku_base=s.cod_producto)) match_sku from wh.stock s`);
await q('lv_match', `select count(distinct cod_producto) n, count(distinct cod_producto) filter (where exists(select 1 from mos.productos p where p.codigo_barra=l.cod_producto)) m_cb from wh.lotes_vencimiento l`);
await q('vd_match', `select count(distinct vd.sku) n, count(distinct vd.sku) filter (where exists(select 1 from mos.productos p where p.sku_base=vd.sku)) m_sku, count(distinct vd.sku) filter (where exists(select 1 from mos.productos p where p.id_producto=vd.sku)) m_id from me.ventas_detalle vd`);
await q('estados', `select distinct estado_envio from me.ventas limit 20`);
await c.end();
