import fs from 'fs';
import pkg from 'pg';
const { Client } = pkg;
const c = new Client({ connectionString: fs.readFileSync('C:/Users/ISO/.sb_db.url','utf8').trim(), ssl:{rejectUnauthorized:false} });
await c.connect();
const q = async (t,s,p)=>{ try{ const r=await c.query(s,p); console.log('###',t); console.dir(r.rows,{depth:4,maxArrayLength:80}); }catch(e){ console.log('###',t,'ERR',e.message); } };
await q('tablas_lote', `select table_schema, table_name from information_schema.tables where (table_name ilike '%lote%' or table_name ilike '%vencim%') order by 1,2`);
await q('promos', `select * from mos.promociones order by updated_at desc nulls last limit 20`);
await q('cols_productos', `select string_agg(column_name||':'||data_type, ' | ' order by ordinal_position) c from information_schema.columns where table_schema='mos' and table_name='productos'`);
await c.end();
