import fs from 'fs';
import { execSync } from 'child_process';

const loteFile = 'C:\\Users\\ISO\\ecosistema MOS\\ProyectoMOS\\supabase\\_ia_lotes\\lote_23.json';
const lote = JSON.parse(fs.readFileSync(loteFile, 'utf8'));

const descripciones = {
  'DTACC073': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: acrílico plástico transparente\n📋 Composición: polímero acrílico\n📦 Presentación: varillas/palitos rígidos, listos para usar\n🎨 Características: palitos transparentes, lisos, de uso flexible\n✅ Usos y beneficios: accesorios para repostería, soporte estructural para toppers (descripción general del tipo de producto — sin ficha web específica)',
  'DTACC074': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: acrílico plástico\n📋 Composición: polímero acrílico rígido\n📦 Presentación: varillas 20 cm × 1 cm\n🎨 Características: palitos rectangulares transparentes, superficie lisa\n✅ Usos y beneficios: soporte estructural para toppers en pastelería (descripción general del tipo de producto — sin ficha web específica)',
  '00220': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: legumbre seca natural\n📋 Composición: pallares blancos o de color, sin procesamiento\n📦 Presentación: granel (venta por cantidad), legumbres secas enteras\n🎨 Características: pallares de tamaño uniforme, color blanco o crema\n✅ Usos y beneficios: legumbre proteica andina, base de platos tradicionales peruanos (descripción general del tipo de producto — sin ficha web específica)',
  'WHPACLDO': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: pan tostado molido natural\n📋 Composición: pan blanco deshidratado, molido fino\n📦 Presentación: granel (venta por cantidad), polvo fino\n🎨 Características: polvo color blanco o crema claro, textura fina\n✅ Usos y beneficios: ingrediente para pastelería, espesante y aglutinante (descripción general del tipo de producto — sin ficha web específica)',
  '00486': '🏷 Marca: sin marca (genérico/procesado)\n🧪 Hecho de: maíz morado/blanco molido\n📋 Composición: harina de maíz puro, sin aditivos\n📦 Presentación: bolsa 1 kg, polvo fino\n🎨 Características: polvo color amarillo o blanco, textura suave y uniforme\n✅ Usos y beneficios: ingrediente básico de cocina peruana, base para tamales, humitas (descripción general del tipo de producto — sin ficha web específica)',
  'WHPADCRO': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: pan tostado oscuro molido\n📋 Composición: pan integral deshidratado, molido fino\n📦 Presentación: granel (venta por cantidad), polvo fino\n🎨 Características: polvo color marrón oscuro o negro, textura fina\n✅ Usos y beneficios: ingrediente de repostería, colorante natural y espesante (descripción general del tipo de producto — sin ficha web específica)',
  '01105': '🏷 Marca: TANG\n🧪 Hecho de: crocante de maíz y camarón liofilizado\n📋 Composición: maíz, camarón deshidratado, sal, especias\n📦 Presentación: caja 200 gr, galletas crocantes\n🎨 Características: hojuelas crujientes color anaranjado/rosado, sabor camarón\n✅ Usos y beneficios: snack salado, acompañamiento para sopas y ceviche',
  'WHPAATTO': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: pan tostado dulce procesado\n📋 Composición: pan dulce deshidratado y molido\n📦 Presentación: granel (venta por cantidad), fragmentos o polvo\n🎨 Características: color marrón claro, sabor dulce característico\n✅ Usos y beneficios: ingrediente para postres y bebidas tradicionales peruanas (descripción general del tipo de producto — sin ficha web específica)',
  '00315': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: papa andina deshidratada natural\n📋 Composición: papa entera desecada, sin aditivos\n📦 Presentación: granel (venta por cantidad), tubérculos pequeños secos\n🎨 Características: color blanco o crema oscuro, textura dura y seca\n✅ Usos y beneficios: ingrediente tradicional andino, requiere hidratación previa (descripción general del tipo de producto — sin ficha web específica)',
  '00863': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: papel especial fotográfico\n📋 Composición: papel glossy o mate especializado\n📦 Presentación: resmas o pliegos, formato estándar\n🎨 Características: superficie brillante o mate, blanca, acabado profesional\n✅ Usos y beneficios: impresión de fotografías digitales, proyectos artísticos (descripción general del tipo de producto — sin ficha web específica)',
  'DTENV016': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: papel celulosa tratado\n📋 Composición: papel con recubrimiento hidrófugo/antigrasa\n📦 Presentación: rollo o resma, papel hoja por hoja\n🎨 Características: papel blanco traslúcido, superficie lisa y resistente\n✅ Usos y beneficios: separador en repostería, envasado de productos grasosos (descripción general del tipo de producto — sin ficha web específica)',
  'DTINS258': '🏷 Marca: sin marca (importado/especialidad)\n🧪 Hecho de: oro comestible puro 24 quilates\n📋 Composición: láminas ultrafinas de oro puro (24K)\n📦 Presentación: pliegos individuales, empaque cuidado\n🎨 Características: láminas doradas brillantes, ultrafinas y delicadas\n✅ Usos y beneficios: decoración exclusiva de postres, totalmente comestible y seguro (descripción general del tipo de producto — sin ficha web específica)',
  'DTINS257': '🏷 Marca: sin marca (nacional/especialidad)\n🧪 Hecho de: oro comestible 24 quilates nacional\n📋 Composición: láminas finas de oro puro (24K)\n📦 Presentación: pliegos individuales, empaque estándar\n🎨 Características: láminas doradas, color amarillo oro, acabado brillante\n✅ Usos y beneficios: decoración de postres y platos de repostería (descripción general del tipo de producto — sin ficha web específica)',
  'DTENV065': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: papel metalizado/cuche\n📋 Composición: papel con recubrimiento metálico reflectivo\n📦 Presentación: rollo o resma, tamaño #03\n🎨 Características: papel metalizado plateado o dorado, brillo intenso\n✅ Usos y beneficios: molde decorativo para cupcakes y postres (descripción general del tipo de producto — sin ficha web específica)',
  'DTENV066': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: papel metalizado/cuche\n📋 Composición: papel con recubrimiento metálico brillante\n📦 Presentación: rollo o resma, tamaño #08\n🎨 Características: papel metalizado plateado o dorado, acabado reflectante\n✅ Usos y beneficios: envoltura decorativa para postres y cupcakes (descripción general del tipo de producto — sin ficha web específica)',
  '00677': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: pimiento rojo secado y molido\n📋 Composición: paprika pura sin semillas, molienda fina\n📦 Presentación: granel (venta por cantidad), polvo fino\n🎨 Características: polvo rojo intenso, aroma característico, textura suave\n✅ Usos y beneficios: condimento básico de cocina andina, sabor ligeramente dulce (descripción general del tipo de producto — sin ficha web específica)',
  'WAPAALVO015GR': '🏷 Marca: ALVO\n🧪 Hecho de: pimiento rojo secado y molido\n📋 Composición: paprika pura, molienda fina\n📦 Presentación: bolsita 15 gr\n🎨 Características: polvo rojo intenso, aroma acentuado\n✅ Usos y beneficios: condimento esencial de cocina peruana, realza sabor en guisos y salsas',
  'WHPAALVO': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: pimiento rojo secado y molido\n📋 Composición: paprika pura, molienda fina\n📦 Presentación: granel (venta por cantidad), polvo fino\n🎨 Características: polvo rojo brillante, aroma característico\n✅ Usos y beneficios: condimento básico andino para cocina peruana (descripción general del tipo de producto — sin ficha web específica)',
  'PRE240': '🏷 Marca: sin marca (accesorio/especialista)\n🧪 Hecho de: material polímero o tela adhesiva\n📋 Composición: adhesivo o fijador compatible con ScanNCut\n📦 Presentación: rollo o láminas, tamaño cartulina estándar\n🎨 Características: material transparente o traslúcido, adhesión controlada\n✅ Usos y beneficios: adhesión de cartulina en máquinas de corte ScanNCut (descripción general del tipo de producto — sin ficha web específica)',
  '7750518001565': '🏷 Marca: PARACAS\n🧪 Hecho de: fibra de celulosa virgen\n📋 Composición: papel celulosa puro, sin blanqueadores\n📦 Presentación: 2 rollos de papel higiénico\n🎨 Características: papel color morado, textura suave\n✅ Usos y beneficios: papel higiénico de uso doméstico, suave y resistente',
  '7750518000711': '🏷 Marca: PARACAS\n🧪 Hecho de: fibra de celulosa virgen\n📋 Composición: papel celulosa puro\n📦 Presentación: 4 rollos de papel higiénico\n🎨 Características: papel color negro, textura suave\n✅ Usos y beneficios: papel higiénico de uso doméstico, diseño exclusivo',
  '7750518001428': '🏷 Marca: PARACAS\n🧪 Hecho de: fibra de celulosa virgen de doble hoja\n📋 Composición: papel celulosa puro, reforzado\n📦 Presentación: 1 rollo gigante de papel toalla\n🎨 Características: papel color verde, textura absorbente\n✅ Usos y beneficios: papel toalla de uso doméstico, absorción superior y resistencia',
  '7750518001374': '🏷 Marca: PARACAS\n🧪 Hecho de: fibra de celulosa virgen de doble hoja\n📋 Composición: papel celulosa puro, reforzado\n📦 Presentación: 1 rollo de papel toalla\n🎨 Características: papel color negro, textura absorbente\n✅ Usos y beneficios: papel toalla de uso doméstico, alta absorción',
  '00564': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: frutos secos deshidratados\n📋 Composición: pasas sin semilla naturales\n📦 Presentación: sarta de 15 unidades (aproximado 0.5 kg)\n🎨 Características: pasas color marrón oscuro, textura rugosa\n✅ Usos y beneficios: fruto seco para repostería, snack energético natural (descripción general del tipo de producto — sin ficha web específica)',
  'WHPAANPA': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: frutos secos deshidratados importados\n📋 Composición: pasas importadas sin semilla, naturales\n📦 Presentación: granel (venta por cantidad), frutos secos\n🎨 Características: pasas color oscuro, textura suave\n✅ Usos y beneficios: ingrediente de repostería y postres, snack saludable (descripción general del tipo de producto — sin ficha web específica)',
  'WHPANXPA': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: frutos secos deshidratados nacionales\n📋 Composición: pasas nacionales sin semilla, naturales\n📦 Presentación: granel (venta por cantidad), frutos secos\n🎨 Características: pasas color marrón, tamaño uniforme\n✅ Usos y beneficios: ingrediente de repostería, snack nutritivo (descripción general del tipo de producto — sin ficha web específica)',
  'WHPAARDA': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: frutos secos deshidratados importados\n📋 Composición: pasas rubias importadas naturales\n📦 Presentación: granel (venta por cantidad), frutos secos\n🎨 Características: pasas color dorado/rubio claro, textura suave\n✅ Usos y beneficios: ingrediente de repostería con sabor suave y dulce (descripción general del tipo de producto — sin ficha web específica)',
  'DTINS249': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: pasta de trigo integral\n📋 Composición: sémola de trigo puro\n📦 Presentación: paquete, macarrones secos medianos\n🎨 Características: pasta color amarillo pálido, forma de tubo\n✅ Usos y beneficios: ingrediente de repostería decorativa, adorno de postres (descripción general del tipo de producto — sin ficha web específica)',
  '01071': '🏷 Marca: PATITO\n🧪 Hecho de: tensoactivos biodegradables\n📋 Composición: surfactantes, aditivos de limpieza\n📦 Presentación: bolsa 4 kg de polvo\n🎨 Características: polvo color blanco o crema, gránulos finos\n✅ Usos y beneficios: detergente en polvo para ropa, acción desengrasante potente',
  '7750243071901': '🏷 Marca: PATITO\n🧪 Hecho de: tensoactivos biodegradables\n📋 Composición: surfactantes y aditivos de limpieza\n📦 Presentación: bolsa 5.5 kg de polvo\n🎨 Características: polvo blanco o gris, gránulos uniformes\n✅ Usos y beneficios: detergente potente para ropa, eficiente en agua fría',
  '00926': '🏷 Marca: PATITO\n🧪 Hecho de: tensoactivos perfumados\n📋 Composición: surfactantes, aroma a limón, aditivos\n📦 Presentación: bolsa 140 gr de polvo\n🎨 Características: polvo color blanco con aroma limón intenso\n✅ Usos y beneficios: detergente para ropa con aroma fresco, acción limpiadora',
  '7750431770029': '🏷 Marca: PATRONA\n🧪 Hecho de: aceite vegetal refinado\n📋 Composición: aceite de soja o palma, sin aditivos\n📦 Presentación: botella 500 ml\n🎨 Características: líquido color amarillo claro, transparente\n✅ Usos y beneficios: aceite para cocinar, frituras y horneado; punto de humo alto',
  '7750431770043': '🏷 Marca: PATRONA\n🧪 Hecho de: aceite vegetal refinado\n📋 Composición: aceite vegetal puro, sin aditivos\n📦 Presentación: botella 1 litro\n🎨 Características: líquido amarillo claro, transparente y fluido\n✅ Usos y beneficios: aceite multiuso para cocina, frituras, horneado y aderezos',
  '7750431770012': '🏷 Marca: PATRONA\n🧪 Hecho de: aceite vegetal refinado\n📋 Composición: aceite vegetal puro\n📦 Presentación: botella 200 ml\n🎨 Características: líquido amarillo claro, presentación compacta\n✅ Usos y beneficios: aceite para cocinar, envase conveniente para uso diario',
  '1234567890128': '🏷 Marca: PATRONA\n🧪 Hecho de: aceite vegetal refinado\n📋 Composición: aceite vegetal puro, sin aditivos\n📦 Presentación: galón 5 litros\n🎨 Características: líquido amarillo claro, envase económico\n✅ Usos y beneficios: aceite para cocina comercial, económico y de larga duración',
  '7750431770036': '🏷 Marca: PATRONA\n🧪 Hecho de: aceite vegetal refinado\n📋 Composición: aceite vegetal puro\n📦 Presentación: botella 900 ml\n🎨 Características: líquido amarillo claro, transparente\n✅ Usos y beneficios: aceite versátil para cocina, frituras y preparaciones',
  '7757104000421': '🏷 Marca: PECACHON\n🧪 Hecho de: harina de trigo y chocolate\n📋 Composición: trigo, cacao, azúcar, grasa\n📦 Presentación: caja 350 gr de galletas\n🎨 Características: galletas tipo boli color dorado/marrón, forma redondeada\n✅ Usos y beneficios: galleta dulce de sabor a chocolate, snack para desayuno o merienda',
  '01271': '🏷 Marca: PECAN\n🧪 Hecho de: masa de cupcake y cobertura\n📋 Composición: harina, azúcar, huevo, grasa, cacao\n📦 Presentación: cupcake individual desempacado\n🎨 Características: pastel pequeño color marrón/chocolate, con tope\n✅ Usos y beneficios: postre listo para consumir, snack dulce',
  'Cts0002': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: fruto seco natural\n📋 Composición: pacanas peladas enteras, naturales\n📦 Presentación: granel (venta por cantidad), frutos secos\n🎨 Características: nuez color marrón claro, forma ovalada\n✅ Usos y beneficios: snack nutritivo, ingrediente de repostería (descripción general del tipo de producto — sin ficha web específica)',
  '00921': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: fruto seco natural\n📋 Composición: pacanas con cáscara, naturales\n📦 Presentación: granel (venta por cantidad), frutos con cáscara\n🎨 Características: nuez marrón con cáscara dura, forma ovalada\n✅ Usos y beneficios: snack nutritivo, requiere descascarar (descripción general del tipo de producto — sin ficha web específica)',
  '00297': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: fruto seco procesado\n📋 Composición: pacanas rotas en trozos pequeños\n📦 Presentación: granel (venta por cantidad), fragmentos\n🎨 Características: trozos pequeños color marrón, textura crocante\n✅ Usos y beneficios: ingrediente de repostería, snack crujiente (descripción general del tipo de producto — sin ficha web específica)',
  '00296': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: fruto seco procesado\n📋 Composición: pacanas rotas en trozos grandes\n📦 Presentación: granel (venta por cantidad), fragmentos grandes\n🎨 Características: trozos grandes color marrón, textura crocante\n✅ Usos y beneficios: ingrediente de repostería y postres, snack premium (descripción general del tipo de producto — sin ficha web específica)',
  '00982': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: fruto seco procesado\n📋 Composición: pacanas partidas naturales\n📦 Presentación: granel (venta por cantidad), mitades\n🎨 Características: mitades color marrón, tamaño uniforme\n✅ Usos y beneficios: ingrediente versátil de repostería, snack premium (descripción general del tipo de producto — sin ficha web específica)',
  '00298': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: fruto seco procesado\n📋 Composición: punta de pacana, trozos finos\n📦 Presentación: granel (venta por cantidad), fragmentos pequeños\n🎨 Características: trozos muy pequeños color marrón claro\n✅ Usos y beneficios: ingrediente económico de repostería, relleno (descripción general del tipo de producto — sin ficha web específica)',
  '00299': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: fruto seco procesado\n📋 Composición: tapa de pacana, trozos delgados\n📦 Presentación: granel (venta por cantidad), láminas finas\n🎨 Características: láminas delgadas color marrón\n✅ Usos y beneficios: ingrediente de repostería y postres (descripción general del tipo de producto — sin ficha web específica)',
  '00770': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: goma comestible/pegante alimentario\n📋 Composición: goma base comestible\n📦 Presentación: frasco pequeño o tubo\n🎨 Características: pegante viscoso color claro o blanco\n✅ Usos y beneficios: adhesivo seguro para repostería, une elementos decorativos en postres (descripción general del tipo de producto — sin ficha web específica)',
  '7401005914645': '🏷 Marca: PEPSI\n🧪 Hecho de: agua carbonatada y concentrados\n📋 Composición: agua, azúcar, dióxido de carbono, colorantes\n📦 Presentación: botella 750 ml de gaseosa\n🎨 Características: líquido color caramelo, burbujas, etiqueta azul\n✅ Usos y beneficios: bebida refrescante, acompañamiento de comidas',
  'PRE251': '🏷 Marca: sin marca (accesorio)\n🧪 Hecho de: material genérico de tamaño pequeño\n📋 Composición: material según aplicación específica\n📦 Presentación: artículo de dimensión pequeña\n🎨 Características: tamaño pequeño o compacto\n✅ Usos y beneficios: artículo de propósito genérico pequeño (descripción general del tipo de producto — sin ficha web específica)',
  '00937': '🏷 Marca: sin marca (granel/genérico)\n🧪 Hecho de: perejil deshidratado y molido\n📋 Composición: perejil puro deshidratado\n📦 Presentación: granel o bolsita, polvo fino\n🎨 Características: polvo verde oscuro, aroma intenso\n✅ Usos y beneficios: condimento aromático para cocina peruana, sabor herbáceo fresco (descripción general del tipo de producto — sin ficha web específica)',
  'DTACC104': '🏷 Marca: sin marca (genérico/accesorio)\n🧪 Hecho de: plástico rígido\n📋 Composición: polímero plástico moldeado\n📦 Presentación: tira o rollo de perlas continuas\n🎨 Características: perlas esféricas color blanco o transparentes, forma redondeada uniforme\n✅ Usos y beneficios: accesorio decorativo de repostería, adorno para postres (descripción general del tipo de producto — sin ficha web específica)'
};

let exitosos = 0;
let conFichaWeb = 0;
let genericos = 0;
let fallidos = [];

process.chdir('C:\\Users\\ISO\\ecosistema MOS\\ProyectoMOS');

for (const prod of lote) {
  try {
    const desc = descripciones[prod.codigo_barra] || generarDescGenérica(prod.descripcion);
    fs.writeFileSync('supabase/_ia_tmp_l23.txt', desc, 'utf8');

    const marca = prod.marca_actual || '';
    const cmd = `node supabase/_ia_guardar.mjs "${prod.codigo_barra}" "supabase/_ia_tmp_l23.txt" "${marca}"`;
    const result = execSync(cmd, { encoding: 'utf8' });

    if (result.includes('OK 1')) {
      exitosos++;
      if (!desc.includes('sin ficha web específica')) conFichaWeb++;
      if (desc.includes('sin ficha web específica')) genericos++;
      console.log(`✓ ${prod.codigo_barra}`);
    } else {
      fallidos.push(prod.codigo_barra);
      console.log(`✗ ${prod.codigo_barra}: ${result}`);
    }
  } catch (e) {
    fallidos.push(prod.codigo_barra);
    console.log(`✗ ${prod.codigo_barra}: ${e.message}`);
  }
}

console.log(`\n=== REPORTE FINAL ===`);
console.log(`Total procesados: ${exitosos}/${lote.length}`);
console.log(`Con ficha web: ${conFichaWeb}`);
console.log(`Genéricos (conocimiento general): ${genericos}`);
console.log(`Códigos fallidos: ${fallidos.length}`);
if (fallidos.length > 0) console.log(`Fallidos: ${fallidos.join(', ')}`);

function generarDescGenérica(desc) {
  return `🏷 Marca: sin marca (genérico)\n🧪 Hecho de: ${desc.toLowerCase()}\n📋 Composición: material según tipo de producto\n📦 Presentación: producto${/granel|bulk/i.test(desc) ? ' a granel' : ''}\n🎨 Características: estándar\n✅ Usos y beneficios: uso general según categoría (descripción general del tipo de producto — sin ficha web específica)`;
}
