import { chromium } from 'playwright';
const SEED = { mos_device_id:'7e57c1a0-de1c-4a7e-b0de-c47a10906474', MOS_SESSION: JSON.stringify({ idPersonal:'TEST-CLAUDE', nombre:'PRUEBA CLAUDE', rol:'MASTER', idSesion:'testclaude1' }) };
const w = ms => new Promise(r=>setTimeout(r,ms));
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1280,height:900}, serviceWorkers:'block' });
const p = await ctx.newPage();
p.on('response', async res => { if (/promo_sugerencias/.test(res.url())) { let t=''; try{t=await res.text();}catch(_){} console.log('>>', res.status(), res.url().slice(-60), t.slice(0,500)); } });
await p.addInitScript(s=>{for(const[k,v]of Object.entries(s))localStorage.setItem(k,v);}, SEED);
await p.goto('https://levo19.github.io/MOS/?nc='+Date.now(), { waitUntil:'domcontentloaded', timeout:60000 });
await w(21000);
await p.evaluate(()=>{const b=[...document.querySelectorAll('button,a')].find(el=>/Entrar a MOS/i.test(el.textContent||'')); if(b)b.click();});
await w(2000);
await p.evaluate(()=>{try{MOS.nav('catalogo');}catch(_){}}); await w(9000);
const out = await p.evaluate(async () => { try { const r = await API.get('getPromoSugerencias', { n: 6 }); return { ok:true, n:(r&&r.data||[]).length, keys:Object.keys(r||{}) }; } catch(e){ return { ok:false, err:String(e.message||e) }; } });
console.log('RESULT', JSON.stringify(out));
await b.close();
